apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-<env>
  namespace: <namespace>
spec:
  provider:
    vault:
      server: https://openbao-active.openbao.svc:8200
      path: secret
      version: v2
      caProvider:
        type: Secret
        namespace: openbao
        name: openbao-server-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: project-template-<env>-<namespace>
          serviceAccountRef:
            name: external-secrets
            audiences:
              - vault
