apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.password | b64enc | quote }}
  userlist.txt: {{ printf "\"%s\" \"%s\"\n" .Values.user .Values.password | b64enc | quote }}
