{{- if not .Values.frontend.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    helm.sh/resource-policy: keep
automountServiceAccountToken: false
{{- end }}
{{- if not .Values.temporalWorker.serviceAccount.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.temporalWorker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-worker
  annotations:
    helm.sh/resource-policy: keep
automountServiceAccountToken: false
{{- end }}
{{- if not .Values.opsApi.serviceAccount.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.opsApi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: ops-api
  annotations:
    helm.sh/resource-policy: keep
automountServiceAccountToken: false
{{- end }}
