/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsTriggerRouteImport } from './routes/workflows/trigger'
import { Route as WorkflowsHistoryRouteImport } from './routes/workflows/history'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as WorkflowsDefinitionsIndexRouteImport } from './routes/workflows/definitions/index'
import { Route as EntitiesEntityTypeIndexRouteImport } from './routes/entities/$entityType/index'
import { Route as WorkflowsExecutionsWorkflowIdRouteImport } from './routes/workflows/executions/$workflowId'
import { Route as WorkflowsDefinitionsNameRouteImport } from './routes/workflows/definitions/$name'
import { Route as EntitiesEntityTypeIdRouteImport } from './routes/entities/$entityType/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsTriggerRoute = WorkflowsTriggerRouteImport.update({
  id: '/workflows/trigger',
  path: '/workflows/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsHistoryRoute = WorkflowsHistoryRouteImport.update({
  id: '/workflows/history',
  path: '/workflows/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsDefinitionsIndexRoute =
  WorkflowsDefinitionsIndexRouteImport.update({
    id: '/workflows/definitions/',
    path: '/workflows/definitions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntitiesEntityTypeIndexRoute = EntitiesEntityTypeIndexRouteImport.update({
  id: '/entities/$entityType/',
  path: '/entities/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsExecutionsWorkflowIdRoute =
  WorkflowsExecutionsWorkflowIdRouteImport.update({
    id: '/workflows/executions/$workflowId',
    path: '/workflows/executions/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsDefinitionsNameRoute =
  WorkflowsDefinitionsNameRouteImport.update({
    id: '/workflows/definitions/$name',
    path: '/workflows/definitions/$name',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntitiesEntityTypeIdRoute = EntitiesEntityTypeIdRouteImport.update({
  id: '/entities/$entityType/$id',
  path: '/entities/$entityType/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/history': typeof WorkflowsHistoryRoute
  '/workflows/trigger': typeof WorkflowsTriggerRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/workflows/definitions/$name': typeof WorkflowsDefinitionsNameRoute
  '/workflows/executions/$workflowId': typeof WorkflowsExecutionsWorkflowIdRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/workflows/definitions/': typeof WorkflowsDefinitionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/history': typeof WorkflowsHistoryRoute
  '/workflows/trigger': typeof WorkflowsTriggerRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/workflows/definitions/$name': typeof WorkflowsDefinitionsNameRoute
  '/workflows/executions/$workflowId': typeof WorkflowsExecutionsWorkflowIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
  '/workflows/definitions': typeof WorkflowsDefinitionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/history': typeof WorkflowsHistoryRoute
  '/workflows/trigger': typeof WorkflowsTriggerRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/workflows/definitions/$name': typeof WorkflowsDefinitionsNameRoute
  '/workflows/executions/$workflowId': typeof WorkflowsExecutionsWorkflowIdRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/workflows/definitions/': typeof WorkflowsDefinitionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflows/$workflowId'
    | '/workflows/history'
    | '/workflows/trigger'
    | '/workflows/'
    | '/entities/$entityType/$id'
    | '/workflows/definitions/$name'
    | '/workflows/executions/$workflowId'
    | '/entities/$entityType/'
    | '/workflows/definitions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workflows/$workflowId'
    | '/workflows/history'
    | '/workflows/trigger'
    | '/workflows'
    | '/entities/$entityType/$id'
    | '/workflows/definitions/$name'
    | '/workflows/executions/$workflowId'
    | '/entities/$entityType'
    | '/workflows/definitions'
  id:
    | '__root__'
    | '/'
    | '/workflows/$workflowId'
    | '/workflows/history'
    | '/workflows/trigger'
    | '/workflows/'
    | '/entities/$entityType/$id'
    | '/workflows/definitions/$name'
    | '/workflows/executions/$workflowId'
    | '/entities/$entityType/'
    | '/workflows/definitions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  WorkflowsHistoryRoute: typeof WorkflowsHistoryRoute
  WorkflowsTriggerRoute: typeof WorkflowsTriggerRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  EntitiesEntityTypeIdRoute: typeof EntitiesEntityTypeIdRoute
  WorkflowsDefinitionsNameRoute: typeof WorkflowsDefinitionsNameRoute
  WorkflowsExecutionsWorkflowIdRoute: typeof WorkflowsExecutionsWorkflowIdRoute
  EntitiesEntityTypeIndexRoute: typeof EntitiesEntityTypeIndexRoute
  WorkflowsDefinitionsIndexRoute: typeof WorkflowsDefinitionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/trigger': {
      id: '/workflows/trigger'
      path: '/workflows/trigger'
      fullPath: '/workflows/trigger'
      preLoaderRoute: typeof WorkflowsTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/history': {
      id: '/workflows/history'
      path: '/workflows/history'
      fullPath: '/workflows/history'
      preLoaderRoute: typeof WorkflowsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/definitions/': {
      id: '/workflows/definitions/'
      path: '/workflows/definitions'
      fullPath: '/workflows/definitions/'
      preLoaderRoute: typeof WorkflowsDefinitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/': {
      id: '/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType/'
      preLoaderRoute: typeof EntitiesEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/executions/$workflowId': {
      id: '/workflows/executions/$workflowId'
      path: '/workflows/executions/$workflowId'
      fullPath: '/workflows/executions/$workflowId'
      preLoaderRoute: typeof WorkflowsExecutionsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/definitions/$name': {
      id: '/workflows/definitions/$name'
      path: '/workflows/definitions/$name'
      fullPath: '/workflows/definitions/$name'
      preLoaderRoute: typeof WorkflowsDefinitionsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$id': {
      id: '/entities/$entityType/$id'
      path: '/entities/$entityType/$id'
      fullPath: '/entities/$entityType/$id'
      preLoaderRoute: typeof EntitiesEntityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  WorkflowsHistoryRoute: WorkflowsHistoryRoute,
  WorkflowsTriggerRoute: WorkflowsTriggerRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  EntitiesEntityTypeIdRoute: EntitiesEntityTypeIdRoute,
  WorkflowsDefinitionsNameRoute: WorkflowsDefinitionsNameRoute,
  WorkflowsExecutionsWorkflowIdRoute: WorkflowsExecutionsWorkflowIdRoute,
  EntitiesEntityTypeIndexRoute: EntitiesEntityTypeIndexRoute,
  WorkflowsDefinitionsIndexRoute: WorkflowsDefinitionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
