#!/usr/bin/env bash
# scripts/verify-stack.sh
#
# Verifies that the full local stack is *actually up and talking* -- not just
# that the logs look clean. Probes every service over the wire and exercises
# the cross-service paths (frontend->Supabase, worker->Supabase, worker/UI->Temporal).
#
# Usage:
#   ./scripts/verify-stack.sh           # human-readable report, exits non-zero on any failure
#   make verify                         # same, via the Makefile wrapper
#
# Exit code 0 = every required check passed. Non-zero = at least one failure.
#
# Requires: a running stack (`make up` / `supabase start` + `docker compose up -d`),
#           docker, curl, and the Supabase CLI on PATH.
set -uo pipefail

# --- config (override via env) ----------------------------------------------
SUPABASE_API="${SUPABASE_API:-http://localhost:54321}"
SUPABASE_STUDIO="${SUPABASE_STUDIO:-http://localhost:54323}"
SUPABASE_INBUCKET="${SUPABASE_INBUCKET:-http://localhost:54324}"
TEMPORAL_UI="${TEMPORAL_UI:-http://localhost:8081}"
WORKER_API="${WORKER_API:-http://localhost:3001}"
FRONTEND="${FRONTEND:-http://localhost:3000}"
DB_CONTAINER="${DB_CONTAINER:-supabase_db_project-template}"
FRONTEND_CONTAINER="${FRONTEND_CONTAINER:-frontend}"
TEMPORAL_CONTAINER="${TEMPORAL_CONTAINER:-temporal}"
TEMPORAL_TASK_QUEUE="${TEMPORAL_TASK_QUEUE:-main}"

PASS=0; FAIL=0; WARN=0

ok()   { printf '  [PASS] %s\n' "$1"; PASS=$((PASS+1)); }
bad()  { printf '  [FAIL] %s\n' "$1"; FAIL=$((FAIL+1)); }
warn() { printf '  [WARN] %s\n' "$1"; WARN=$((WARN+1)); }
hdr()  { printf '\n== %s ==\n' "$1"; }

# curl helper: prints the HTTP status code (000 if unreachable).
code() { curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$@" 2>/dev/null || echo 000; }
# curl helper: prints the body.
body() { curl -s --max-time 10 "$@" 2>/dev/null || true; }

# psql helper against the Supabase Postgres container.
psql_q() {
  docker exec "$DB_CONTAINER" psql -U postgres -d postgres -tAc "$1" 2>/dev/null | tr -d '\r'
}

# Resolve live Supabase anon/service keys (per-instance, generated by `supabase start`).
ANON_KEY=""; SERVICE_KEY=""
if command -v supabase >/dev/null 2>&1; then
  status_env="$(supabase status -o env 2>/dev/null || true)"
  ANON_KEY="$(printf '%s\n' "$status_env" | sed -n 's/^ANON_KEY="\(.*\)"$/\1/p')"
  SERVICE_KEY="$(printf '%s\n' "$status_env" | sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"$/\1/p')"
fi

# ----------------------------------------------------------------------------
# STEP 2 -- Supabase backend (schema, auth, data layer, seed)
# ----------------------------------------------------------------------------
hdr "STEP 2: Supabase backend (Postgres + API + Auth + Storage)"

if [ -n "$ANON_KEY" ]; then ok "resolved Supabase anon/service keys from 'supabase status'"; else
  bad "could not resolve Supabase keys -- is Supabase running?"; fi

# service_role bypasses the grant lockdown, so a 200 here proves PostgREST is up
# AND able to serve the schema. (anon correctly gets 401 under the lockdown -- that
# path is asserted separately below.)
c="$(code -H "apikey: ${SERVICE_KEY}" -H "Authorization: Bearer ${SERVICE_KEY}" "${SUPABASE_API}/rest/v1/")"
[ "$c" = "200" ] && ok "Supabase REST (PostgREST) reachable at ${SUPABASE_API}/rest/v1/ (HTTP $c, service role)" \
                 || bad "Supabase REST not reachable (HTTP $c)"

c="$(code "${SUPABASE_API}/auth/v1/health")"
[ "$c" = "200" ] && ok "Supabase Auth (GoTrue) healthy at /auth/v1/health (HTTP $c)" \
                 || bad "Supabase Auth not healthy (HTTP $c)"

c="$(code -H "apikey: ${ANON_KEY}" "${SUPABASE_API}/storage/v1/version")"
[ "$c" = "200" ] && ok "Supabase Storage reachable (/storage/v1/version HTTP $c)" \
                 || warn "Supabase Storage check inconclusive (HTTP $c)"

# Supabase Studio = the Supabase UI required by the exercise ("UIs reachable").
# Studio answers with a redirect (307) to its project route -- any 2xx/3xx is "up".
c="$(code "${SUPABASE_STUDIO}")"
case "$c" in
  200|301|302|307|308) ok "Supabase Studio UI reachable at ${SUPABASE_STUDIO} (HTTP $c)";;
  *) bad "Supabase Studio UI not reachable (HTTP $c)";;
esac

# Postgres reachable + schema present
if [ "$(psql_q 'SELECT 1;')" = "1" ]; then
  ok "Postgres reachable via container ${DB_CONTAINER}"
else
  bad "Postgres not reachable via container ${DB_CONTAINER}"
fi

migs="$(psql_q 'SELECT count(*) FROM supabase_migrations.schema_migrations;')"
[ "${migs:-0}" -ge 1 ] 2>/dev/null && ok "migrations applied: ${migs} rows in supabase_migrations.schema_migrations" \
                                    || bad "no applied migrations found"

core_tables="$(psql_q "SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('entities','entity_versions','relationships_v2','fact_types','entity_facts','time_series_points');")"
[ "${core_tables:-0}" = "6" ] && ok "core ontology tables present (6/6)" \
                              || bad "core ontology tables incomplete (${core_tables}/6)"

wf_tables="$(psql_q "SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('workflow_definitions','workflow_executions','documents');")"
[ "${wf_tables:-0}" = "3" ] && ok "workflow/analytics tables present (workflow_definitions, workflow_executions, documents)" \
                            || bad "workflow/analytics tables incomplete (${wf_tables}/3)"

# Security model: this schema locks down DIRECT table access via REVOKEd grants
# + SECURITY DEFINER RPCs (not row-level policies). Prove anon is denied a direct
# read -- a 401/403 here is the *expected*, healthy lockdown signal.
lockdown="$(code -H "apikey: ${ANON_KEY}" -H "Authorization: Bearer ${ANON_KEY}" "${SUPABASE_API}/rest/v1/entities?select=id&limit=1")"
{ [ "$lockdown" = "401" ] || [ "$lockdown" = "403" ]; } \
  && ok "auth lockdown active: anon denied direct table read (HTTP $lockdown; access is via RPCs/service role)" \
  || warn "anon direct table read returned HTTP $lockdown (expected 401/403 under grant lockdown)"

# ----------------------------------------------------------------------------
# STEP 3 -- Frontend wired to Supabase
# ----------------------------------------------------------------------------
hdr "STEP 3: Frontend (Vite/React) wired to Supabase"

c="$(code "${FRONTEND}")"
[ "$c" = "200" ] && ok "Frontend serving at ${FRONTEND} (HTTP $c)" \
                 || bad "Frontend not serving (HTTP $c)"

html="$(body "${FRONTEND}")"
printf '%s' "$html" | grep -qi '<div id="root"' && ok "Frontend HTML shell present (#root mount point)" \
                                                 || warn "Frontend HTML shell not recognised"

# The runtime entrypoint substitutes __VITE_*__ placeholders across the built JS.
# The Supabase client lives in a separate chunk (supabase-*.js), so inspect the
# whole served dist inside the container rather than a single HTML-linked asset.
inj_ph="$(docker exec "$FRONTEND_CONTAINER" sh -c "grep -rl '__VITE_' /tmp/frontend-dist/assets 2>/dev/null" 2>/dev/null)"
inj_url="$(docker exec "$FRONTEND_CONTAINER" sh -c "grep -rl 'localhost:54321' /tmp/frontend-dist/assets 2>/dev/null | head -1" 2>/dev/null)"
if [ -n "$inj_ph" ]; then
  bad "Frontend bundle still contains un-injected __VITE_* placeholder(s)"
elif [ -n "$inj_url" ]; then
  ok "Frontend wired to Supabase: real :54321 URL injected into served bundle ($(basename "$inj_url"))"
else
  warn "Frontend bundle: could not confirm Supabase URL injection"
fi

# Cross-service: the anon key the frontend bundle carries actually authenticates
# to Supabase. /auth/v1/settings requires a valid apikey and is independent of
# table grants/RLS, so it cleanly proves the anon key is accepted.
c="$(code -H "apikey: ${ANON_KEY}" "${SUPABASE_API}/auth/v1/settings")"
[ "$c" = "200" ] && ok "Frontend->Supabase path OK: anon key accepted by Supabase Auth (/auth/v1/settings HTTP $c)" \
                 || bad "Frontend->Supabase path failed: anon key rejected (HTTP $c)"

# ----------------------------------------------------------------------------
# STEP 4 -- Temporal + worker, and cross-service connectivity
# ----------------------------------------------------------------------------
hdr "STEP 4: Temporal UI/server, worker, and cross-service wiring"

c="$(code "${TEMPORAL_UI}")"
[ "$c" = "200" ] && ok "Temporal UI reachable at ${TEMPORAL_UI} (HTTP $c)" \
                 || bad "Temporal UI not reachable (HTTP $c)"

ns="$(body "${TEMPORAL_UI}/api/v1/namespaces")"
printf '%s' "$ns" | grep -q '"default"' && ok "Temporal UI -> Temporal server OK: 'default' namespace listed via UI API" \
                                         || bad "Temporal UI cannot reach Temporal server (no namespaces returned)"

# Temporal server gRPC: describe the task queue and confirm the worker is polling it.
tq="$(docker exec "$TEMPORAL_CONTAINER" tctl --address "${TEMPORAL_CONTAINER}:7233" taskqueue describe --taskqueue "${TEMPORAL_TASK_QUEUE}" 2>/dev/null || true)"
if printf '%s' "$tq" | grep -qiE 'Identity|Poller|LastAccessTime'; then
  ok "Worker->Temporal OK: poller(s) registered on task queue '${TEMPORAL_TASK_QUEUE}'"
else
  warn "Worker->Temporal: no pollers reported yet on task queue '${TEMPORAL_TASK_QUEUE}' (worker may still be starting)"
fi

# Worker HTTP health
c="$(code "${WORKER_API}/health")"
[ "$c" = "200" ] && ok "Temporal worker HTTP health OK at ${WORKER_API}/health (HTTP $c)" \
                 || bad "Temporal worker HTTP health failed (HTTP $c)"

# Cross-service: worker -> Supabase REST (this endpoint queries the DB via service key)
exec_code="$(code "${WORKER_API}/workflows/executions?limit=1")"
exec_body="$(body "${WORKER_API}/workflows/executions?limit=1")"
if [ "$exec_code" = "200" ] && printf '%s' "$exec_body" | grep -qE '^\s*\['; then
  ok "Worker->Supabase OK: /workflows/executions returned JSON from Postgres (HTTP $exec_code)"
else
  bad "Worker->Supabase failed: /workflows/executions (HTTP $exec_code) body=${exec_body:0:120}"
fi

# ----------------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------------
hdr "SUMMARY"
printf '  PASS=%d  WARN=%d  FAIL=%d\n' "$PASS" "$WARN" "$FAIL"
if [ "$FAIL" -gt 0 ]; then
  printf '\nRESULT: STACK NOT FULLY CONNECTED (%d failing check(s)).\n' "$FAIL"
  exit 1
fi
printf '\nRESULT: STACK IS UP AND SERVICES ARE TALKING. Supabase + Temporal UIs reachable.\n'
exit 0
